### ISSUE TITLE
Tahák na třídy

### ISSUE THREAD

**Issue by hroncok** [encukou/cheatsheets#11]
...by se mi velmi hodil na můj workshop na asteroidy. @encukou je něco rozpracovaného (klidně jen seznam věcí, co tam dát), nebo mám začít from scratch?

**Comment by encukou** [comment]
Rozpracovaného nic nemám.

**Comment by hroncok** [comment]
Chtěl bych tam navalit asi tohle:

```python
class Zviratko:  # Vlastní třída, neboli typ
    def __init__(self, jmeno):  # Inicializace objektu, může přebírat argumenty
        self.jmeno = jmeno      # Nastavení atributu objektu

    def snez(self, jidlo):      # Metoda - první argument je **self**
        print(self.jmeno, "jí", jidlo) # Přístup k atributu objektu


class Kotatko(Zviratko):  # Dědičnost (koťátko je druh zvířátka)
    def zamnoukej(self):  # Metoda specifická pro koťátka
        print(self.jmeno, "mňau!")


class Prasatko(Zviratko):  # Dědičnost (prasátko je druh zvířátka)
    def zakvic(self):  # Metoda specifická pro prasátka
        print(self.jmeno, "kví!")

    def snez(self, jidlo):  # Přepisování metody předka
        print(self.jmeno, "se před jídlem válí v bahně!")
        super().snez(jidlo)  # Volání metody předka
        print(self.jmeno, "se po jídle taky válí v bahně!")


prasatko = Prasatko('Ťulda')  # Vytvoření objektu (instance) třídy
# (šipky k počátečním písmenům) Objekty píšeme s malým, třídy s velkým
# (šipka z Ťulda na Zviratko.__init__ jmeno)

prasatko.snez('žalud')  # Volání metody
# (šipka z prasatko na Prasatko.snez self)

karlicka = Prasatko('Karlička')  # Objektů jedné třídy může být víc
print(karlicka.jmeno) # Můžeme se dívat na jejich atributy
karlicka.jmeno = 'Karla' # A taky je měnit

mikes = Kotatko('Mikeš')

for zviratko in [prasatko, karlicka, mikes, Kotatko('Mourek')]:
    # (následující řádek někde bokem označím jako polymorfizmus)
    zviratko.snez('papání')  #  Nevíme jestli to je prasátko nebo koťátko, ale to nevadí, tohle funguje

    # (následující 2 řádke někde bokem označím jako kontrola typu)
    isinstance(zviratko, Zviratko)  # Je instancí zvířátka? Ano, je, isinstance platí i pro potomky
    type(zviratko) == Zviratko  # Je třída objektu přesně Zviratko? Ne, Kotakto či Prasatko != Zviratko
```

**Comment by encukou** [comment]
* [x] Doporučuju do příkladu `isinstance` dát spíš `str`. `int` není jediný celočíselný typ (a už vůbec ne číselný). Když používáš `isinstance` s číslama, měl by sis měl uvědomit co vlastně přesně chceš (např. [numbers.Integral](https://docs.python.org/3/library/numbers.html#numbers.Integral)).
* [x] Pro `# Přístup k atributu objektu` bych radši přidal zvláštní řádek jen s tím přístupem k atributu. `format` dělá začátečníkům problémy sám o sobě.
* [x] `super(self)` je špatně, má to být jen `super()` (případně `super(Prasatko, self)`.
* [ ] Popřemýšlej jestli představení `isinstance()` nedat až dolů, k posledním dvěma řádkům, a nekombinovat tam typechecking s polymorfismem. 

Formátem to odbíhá od taháků jako přehledů encyklopedických znalostí směrem někam ke [Learn X in Y minutes](https://learnxinyminutes.com/docs/python3/). Zatím na takové věci nemáme nic lepšího, ale dlouhodobě bych přemýšlel jak to oddělit a zpracovat rozumněji.

**Comment by hroncok** [comment]
Dal jsem typechecking až dolů, ale tím jsem ho zkombinoval s polymorfismem. Nevím, jestlis to myslel takto.

Přijde mi to jako tahák k přehledu jak se co dělá a s kapkou informace o tom, jak se to chová. Nenapadlo mě to pojmout jinak než souvislým kódem.

Na můj workshop předpokládám znalost tříd z jiných programovacích jazyků. Na PyLadies se předpokládá, že proběhl výklad a tohle je tahák na příště (třeba k asteroidům). Myslím si, že to může fungovat.

**Comment by encukou** [comment]
To `print(self.jmeno, "mi chutná!")` nedává moc smysl :)

Myslel jsem to tak, že by `for` ukazoval polymorfismus, a typechecking by byl úplně bokem. Ale to už je nitpicking.

Jo, formát bude fungovat. Zvlášť jako první pokus podobnou věc udělat :)

**Comment by hroncok** [comment]
Opraveno, vyzkoušeno.

```
Ťulda se před jídlem válí v bahně!
Ťulda jí žalud
Ťulda se po jídle taky válí v bahně!
Karlička
Ťulda se před jídlem válí v bahně!
Ťulda jí papání
Ťulda se po jídle taky válí v bahně!
Karla se před jídlem válí v bahně!
Karla jí papání
Karla se po jídle taky válí v bahně!
Mikeš jí papání
Mourek jí papání

```
