### ISSUE TITLE
Tahák na slovníky - chyba

### ISSUE THREAD

**Issue by Kobzol** [encukou/cheatsheets#17]
V taháku na slovníky je toto:

```python
if d:     # Je-li slovník prázdný
```

Popis je naopak, myslím, že přehlednější by bylo něco jako `Je-li slovník neprázdný` nebo `Není-li slovník prázdný`.

Mimochodem super projektík, hodí se pro výuku :+1:

**Comment by hroncok** [comment]
Souhlasím.
